name: Logtalk

on: [push]

jobs:
  logtalk:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Install ECLiPSe
        uses: logtalk-actions/setup-eclipse@master
        with:
          eclipse-version: '7.0_50'
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: latest
      - name: Run Logtalk aliases example tests
        run: eclipselgt -e "{aliases(tester)}" -e halt
