name: Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Install ECLiPSe
        uses: logtalk-actions/setup-eclipse@master
        with:
          eclipse-version: '7.0_50'
      - name: Run trivial sanity test
        run: eclipse -e true -e halt
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: latest
          logtalk-tool-dependencies: false
      - name: Run Logtalk aliases example tests
        run: cd "$LOGTALKUSER/examples/aliases" && logtalk_tester -p eclipse
